//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoucherWebService.FinVoucher {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoucherData", Namespace="http://schemas.datacontract.org/2004/07/SystemGroup.Financial.IVoucherManagement." +
        "Common")]
    [System.SerializableAttribute()]
    public partial class VoucherData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuxiliaryNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long BranchRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Description_EnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long FiscalYearRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCurrencyBasedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExternalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LedgerRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VoucherWebService.FinVoucher.VoucherState StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VoucherWebService.FinVoucher.VoucherItemData[] VoucherItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VoucherWebService.FinVoucher.ReferenceInfo[] VoucherReferenceInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VoucherTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoucherTypeOwnerSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> VoucherTypeRefField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuxiliaryNumber {
            get {
                return this.AuxiliaryNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AuxiliaryNumberField, value) != true)) {
                    this.AuxiliaryNumberField = value;
                    this.RaisePropertyChanged("AuxiliaryNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long BranchRef {
            get {
                return this.BranchRefField;
            }
            set {
                if ((this.BranchRefField.Equals(value) != true)) {
                    this.BranchRefField = value;
                    this.RaisePropertyChanged("BranchRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((this.CreatorField.Equals(value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorName {
            get {
                return this.CreatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorNameField, value) != true)) {
                    this.CreatorNameField = value;
                    this.RaisePropertyChanged("CreatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description_En {
            get {
                return this.Description_EnField;
            }
            set {
                if ((object.ReferenceEquals(this.Description_EnField, value) != true)) {
                    this.Description_EnField = value;
                    this.RaisePropertyChanged("Description_En");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long FiscalYearRef {
            get {
                return this.FiscalYearRefField;
            }
            set {
                if ((this.FiscalYearRefField.Equals(value) != true)) {
                    this.FiscalYearRefField = value;
                    this.RaisePropertyChanged("FiscalYearRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCurrencyBased {
            get {
                return this.IsCurrencyBasedField;
            }
            set {
                if ((this.IsCurrencyBasedField.Equals(value) != true)) {
                    this.IsCurrencyBasedField = value;
                    this.RaisePropertyChanged("IsCurrencyBased");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExternal {
            get {
                return this.IsExternalField;
            }
            set {
                if ((this.IsExternalField.Equals(value) != true)) {
                    this.IsExternalField = value;
                    this.RaisePropertyChanged("IsExternal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LedgerRef {
            get {
                return this.LedgerRefField;
            }
            set {
                if ((this.LedgerRefField.Equals(value) != true)) {
                    this.LedgerRefField = value;
                    this.RaisePropertyChanged("LedgerRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VoucherWebService.FinVoucher.VoucherState State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateTitle {
            get {
                return this.StateTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.StateTitleField, value) != true)) {
                    this.StateTitleField = value;
                    this.RaisePropertyChanged("StateTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VoucherWebService.FinVoucher.VoucherItemData[] VoucherItems {
            get {
                return this.VoucherItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherItemsField, value) != true)) {
                    this.VoucherItemsField = value;
                    this.RaisePropertyChanged("VoucherItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VoucherWebService.FinVoucher.ReferenceInfo[] VoucherReferenceInfo {
            get {
                return this.VoucherReferenceInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherReferenceInfoField, value) != true)) {
                    this.VoucherReferenceInfoField = value;
                    this.RaisePropertyChanged("VoucherReferenceInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VoucherTypeCode {
            get {
                return this.VoucherTypeCodeField;
            }
            set {
                if ((this.VoucherTypeCodeField.Equals(value) != true)) {
                    this.VoucherTypeCodeField = value;
                    this.RaisePropertyChanged("VoucherTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoucherTypeOwnerSystem {
            get {
                return this.VoucherTypeOwnerSystemField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherTypeOwnerSystemField, value) != true)) {
                    this.VoucherTypeOwnerSystemField = value;
                    this.RaisePropertyChanged("VoucherTypeOwnerSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> VoucherTypeRef {
            get {
                return this.VoucherTypeRefField;
            }
            set {
                if ((this.VoucherTypeRefField.Equals(value) != true)) {
                    this.VoucherTypeRefField = value;
                    this.RaisePropertyChanged("VoucherTypeRef");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoucherState", Namespace="http://schemas.datacontract.org/2004/07/SystemGroup.Financial.IVoucherManagement." +
        "Common")]
    public enum VoucherState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WithNoRevision = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Note = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoucherItemData", Namespace="http://schemas.datacontract.org/2004/07/SystemGroup.Financial.IVoucherManagement." +
        "Common")]
    [System.SerializableAttribute()]
    public partial class VoucherItemData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BaseCurrencyAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> BaseCurrencyExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BaseCurrencyExchangeRateRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BaseCurrencyPrecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> BaseCurrencyRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaseCurrencyTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrencyAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrencyCreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CurrencyDebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrencyPrecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> CurrencyRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DL4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DL5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DL6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DL7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DL8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DL9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DLLevel4TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DLLevel5TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DLLevel6TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DLLevel7TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DLLevel8TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DLLevel9TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DLTypeRef4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DLTypeRef5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DLTypeRef6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DLTypeRef7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DLTypeRef8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> DLTypeRef9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> DebitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Description_EnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExtraDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FollowUpDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FollowUpNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSLTraceableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ItemOrServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfSLDLLevelsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> OperationalCurrencyExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> OperationalCurrencyExchangeRateRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperationalCurrencyPrecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PurchaseOrSaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SLCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SLRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SLTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TaxAccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TaxStateTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TransactionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BaseCurrencyAmount {
            get {
                return this.BaseCurrencyAmountField;
            }
            set {
                if ((this.BaseCurrencyAmountField.Equals(value) != true)) {
                    this.BaseCurrencyAmountField = value;
                    this.RaisePropertyChanged("BaseCurrencyAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> BaseCurrencyExchangeRate {
            get {
                return this.BaseCurrencyExchangeRateField;
            }
            set {
                if ((this.BaseCurrencyExchangeRateField.Equals(value) != true)) {
                    this.BaseCurrencyExchangeRateField = value;
                    this.RaisePropertyChanged("BaseCurrencyExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BaseCurrencyExchangeRateRef {
            get {
                return this.BaseCurrencyExchangeRateRefField;
            }
            set {
                if ((this.BaseCurrencyExchangeRateRefField.Equals(value) != true)) {
                    this.BaseCurrencyExchangeRateRefField = value;
                    this.RaisePropertyChanged("BaseCurrencyExchangeRateRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseCurrencyPrecision {
            get {
                return this.BaseCurrencyPrecisionField;
            }
            set {
                if ((this.BaseCurrencyPrecisionField.Equals(value) != true)) {
                    this.BaseCurrencyPrecisionField = value;
                    this.RaisePropertyChanged("BaseCurrencyPrecision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> BaseCurrencyRef {
            get {
                return this.BaseCurrencyRefField;
            }
            set {
                if ((this.BaseCurrencyRefField.Equals(value) != true)) {
                    this.BaseCurrencyRefField = value;
                    this.RaisePropertyChanged("BaseCurrencyRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BaseCurrencyTitle {
            get {
                return this.BaseCurrencyTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.BaseCurrencyTitleField, value) != true)) {
                    this.BaseCurrencyTitleField = value;
                    this.RaisePropertyChanged("BaseCurrencyTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrencyAmount {
            get {
                return this.CurrencyAmountField;
            }
            set {
                if ((this.CurrencyAmountField.Equals(value) != true)) {
                    this.CurrencyAmountField = value;
                    this.RaisePropertyChanged("CurrencyAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrencyCredit {
            get {
                return this.CurrencyCreditField;
            }
            set {
                if ((this.CurrencyCreditField.Equals(value) != true)) {
                    this.CurrencyCreditField = value;
                    this.RaisePropertyChanged("CurrencyCredit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CurrencyDebit {
            get {
                return this.CurrencyDebitField;
            }
            set {
                if ((this.CurrencyDebitField.Equals(value) != true)) {
                    this.CurrencyDebitField = value;
                    this.RaisePropertyChanged("CurrencyDebit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyPrecision {
            get {
                return this.CurrencyPrecisionField;
            }
            set {
                if ((this.CurrencyPrecisionField.Equals(value) != true)) {
                    this.CurrencyPrecisionField = value;
                    this.RaisePropertyChanged("CurrencyPrecision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> CurrencyRef {
            get {
                return this.CurrencyRefField;
            }
            set {
                if ((this.CurrencyRefField.Equals(value) != true)) {
                    this.CurrencyRefField = value;
                    this.RaisePropertyChanged("CurrencyRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyTitle {
            get {
                return this.CurrencyTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyTitleField, value) != true)) {
                    this.CurrencyTitleField = value;
                    this.RaisePropertyChanged("CurrencyTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DL4 {
            get {
                return this.DL4Field;
            }
            set {
                if ((object.ReferenceEquals(this.DL4Field, value) != true)) {
                    this.DL4Field = value;
                    this.RaisePropertyChanged("DL4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DL5 {
            get {
                return this.DL5Field;
            }
            set {
                if ((object.ReferenceEquals(this.DL5Field, value) != true)) {
                    this.DL5Field = value;
                    this.RaisePropertyChanged("DL5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DL6 {
            get {
                return this.DL6Field;
            }
            set {
                if ((object.ReferenceEquals(this.DL6Field, value) != true)) {
                    this.DL6Field = value;
                    this.RaisePropertyChanged("DL6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DL7 {
            get {
                return this.DL7Field;
            }
            set {
                if ((object.ReferenceEquals(this.DL7Field, value) != true)) {
                    this.DL7Field = value;
                    this.RaisePropertyChanged("DL7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DL8 {
            get {
                return this.DL8Field;
            }
            set {
                if ((object.ReferenceEquals(this.DL8Field, value) != true)) {
                    this.DL8Field = value;
                    this.RaisePropertyChanged("DL8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DL9 {
            get {
                return this.DL9Field;
            }
            set {
                if ((object.ReferenceEquals(this.DL9Field, value) != true)) {
                    this.DL9Field = value;
                    this.RaisePropertyChanged("DL9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DLLevel4Title {
            get {
                return this.DLLevel4TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DLLevel4TitleField, value) != true)) {
                    this.DLLevel4TitleField = value;
                    this.RaisePropertyChanged("DLLevel4Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DLLevel5Title {
            get {
                return this.DLLevel5TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DLLevel5TitleField, value) != true)) {
                    this.DLLevel5TitleField = value;
                    this.RaisePropertyChanged("DLLevel5Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DLLevel6Title {
            get {
                return this.DLLevel6TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DLLevel6TitleField, value) != true)) {
                    this.DLLevel6TitleField = value;
                    this.RaisePropertyChanged("DLLevel6Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DLLevel7Title {
            get {
                return this.DLLevel7TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DLLevel7TitleField, value) != true)) {
                    this.DLLevel7TitleField = value;
                    this.RaisePropertyChanged("DLLevel7Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DLLevel8Title {
            get {
                return this.DLLevel8TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DLLevel8TitleField, value) != true)) {
                    this.DLLevel8TitleField = value;
                    this.RaisePropertyChanged("DLLevel8Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DLLevel9Title {
            get {
                return this.DLLevel9TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.DLLevel9TitleField, value) != true)) {
                    this.DLLevel9TitleField = value;
                    this.RaisePropertyChanged("DLLevel9Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DLTypeRef4 {
            get {
                return this.DLTypeRef4Field;
            }
            set {
                if ((this.DLTypeRef4Field.Equals(value) != true)) {
                    this.DLTypeRef4Field = value;
                    this.RaisePropertyChanged("DLTypeRef4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DLTypeRef5 {
            get {
                return this.DLTypeRef5Field;
            }
            set {
                if ((this.DLTypeRef5Field.Equals(value) != true)) {
                    this.DLTypeRef5Field = value;
                    this.RaisePropertyChanged("DLTypeRef5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DLTypeRef6 {
            get {
                return this.DLTypeRef6Field;
            }
            set {
                if ((this.DLTypeRef6Field.Equals(value) != true)) {
                    this.DLTypeRef6Field = value;
                    this.RaisePropertyChanged("DLTypeRef6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DLTypeRef7 {
            get {
                return this.DLTypeRef7Field;
            }
            set {
                if ((this.DLTypeRef7Field.Equals(value) != true)) {
                    this.DLTypeRef7Field = value;
                    this.RaisePropertyChanged("DLTypeRef7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DLTypeRef8 {
            get {
                return this.DLTypeRef8Field;
            }
            set {
                if ((this.DLTypeRef8Field.Equals(value) != true)) {
                    this.DLTypeRef8Field = value;
                    this.RaisePropertyChanged("DLTypeRef8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> DLTypeRef9 {
            get {
                return this.DLTypeRef9Field;
            }
            set {
                if ((this.DLTypeRef9Field.Equals(value) != true)) {
                    this.DLTypeRef9Field = value;
                    this.RaisePropertyChanged("DLTypeRef9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Debit {
            get {
                return this.DebitField;
            }
            set {
                if ((this.DebitField.Equals(value) != true)) {
                    this.DebitField = value;
                    this.RaisePropertyChanged("Debit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description_En {
            get {
                return this.Description_EnField;
            }
            set {
                if ((object.ReferenceEquals(this.Description_EnField, value) != true)) {
                    this.Description_EnField = value;
                    this.RaisePropertyChanged("Description_En");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExtraData {
            get {
                return this.ExtraDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtraDataField, value) != true)) {
                    this.ExtraDataField = value;
                    this.RaisePropertyChanged("ExtraData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FollowUpDate {
            get {
                return this.FollowUpDateField;
            }
            set {
                if ((this.FollowUpDateField.Equals(value) != true)) {
                    this.FollowUpDateField = value;
                    this.RaisePropertyChanged("FollowUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FollowUpNumber {
            get {
                return this.FollowUpNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FollowUpNumberField, value) != true)) {
                    this.FollowUpNumberField = value;
                    this.RaisePropertyChanged("FollowUpNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSLTraceable {
            get {
                return this.IsSLTraceableField;
            }
            set {
                if ((this.IsSLTraceableField.Equals(value) != true)) {
                    this.IsSLTraceableField = value;
                    this.RaisePropertyChanged("IsSLTraceable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ItemOrService {
            get {
                return this.ItemOrServiceField;
            }
            set {
                if ((this.ItemOrServiceField.Equals(value) != true)) {
                    this.ItemOrServiceField = value;
                    this.RaisePropertyChanged("ItemOrService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfSLDLLevels {
            get {
                return this.NumberOfSLDLLevelsField;
            }
            set {
                if ((this.NumberOfSLDLLevelsField.Equals(value) != true)) {
                    this.NumberOfSLDLLevelsField = value;
                    this.RaisePropertyChanged("NumberOfSLDLLevels");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> OperationalCurrencyExchangeRate {
            get {
                return this.OperationalCurrencyExchangeRateField;
            }
            set {
                if ((this.OperationalCurrencyExchangeRateField.Equals(value) != true)) {
                    this.OperationalCurrencyExchangeRateField = value;
                    this.RaisePropertyChanged("OperationalCurrencyExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> OperationalCurrencyExchangeRateRef {
            get {
                return this.OperationalCurrencyExchangeRateRefField;
            }
            set {
                if ((this.OperationalCurrencyExchangeRateRefField.Equals(value) != true)) {
                    this.OperationalCurrencyExchangeRateRefField = value;
                    this.RaisePropertyChanged("OperationalCurrencyExchangeRateRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperationalCurrencyPrecision {
            get {
                return this.OperationalCurrencyPrecisionField;
            }
            set {
                if ((this.OperationalCurrencyPrecisionField.Equals(value) != true)) {
                    this.OperationalCurrencyPrecisionField = value;
                    this.RaisePropertyChanged("OperationalCurrencyPrecision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PurchaseOrSale {
            get {
                return this.PurchaseOrSaleField;
            }
            set {
                if ((this.PurchaseOrSaleField.Equals(value) != true)) {
                    this.PurchaseOrSaleField = value;
                    this.RaisePropertyChanged("PurchaseOrSale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNumber {
            get {
                return this.RowNumberField;
            }
            set {
                if ((this.RowNumberField.Equals(value) != true)) {
                    this.RowNumberField = value;
                    this.RaisePropertyChanged("RowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SLCode {
            get {
                return this.SLCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SLCodeField, value) != true)) {
                    this.SLCodeField = value;
                    this.RaisePropertyChanged("SLCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SLRef {
            get {
                return this.SLRefField;
            }
            set {
                if ((this.SLRefField.Equals(value) != true)) {
                    this.SLRefField = value;
                    this.RaisePropertyChanged("SLRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SLTitle {
            get {
                return this.SLTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.SLTitleField, value) != true)) {
                    this.SLTitleField = value;
                    this.RaisePropertyChanged("SLTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TaxAccountType {
            get {
                return this.TaxAccountTypeField;
            }
            set {
                if ((this.TaxAccountTypeField.Equals(value) != true)) {
                    this.TaxAccountTypeField = value;
                    this.RaisePropertyChanged("TaxAccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TaxStateType {
            get {
                return this.TaxStateTypeField;
            }
            set {
                if ((this.TaxStateTypeField.Equals(value) != true)) {
                    this.TaxStateTypeField = value;
                    this.RaisePropertyChanged("TaxStateType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((this.TransactionTypeField.Equals(value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReferenceInfo", Namespace="http://schemas.datacontract.org/2004/07/SystemGroup.Financial.IVoucherManagement." +
        "Common")]
    [System.SerializableAttribute()]
    public partial class ReferenceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> Descriminatork__BackingFieldField;
        
        private string Descriptionk__BackingFieldField;
        
        private int MasterEntityCodek__BackingFieldField;
        
        private long MasterReferenceIDk__BackingFieldField;
        
        private int OriginalEntityCodek__BackingFieldField;
        
        private long OriginalReferenceIDk__BackingFieldField;
        
        private string ReferenceNumberk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Descriminator>k__BackingField", IsRequired=true)]
        public System.Nullable<int> Descriminatork__BackingField {
            get {
                return this.Descriminatork__BackingFieldField;
            }
            set {
                if ((this.Descriminatork__BackingFieldField.Equals(value) != true)) {
                    this.Descriminatork__BackingFieldField = value;
                    this.RaisePropertyChanged("Descriminatork__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Description>k__BackingField", IsRequired=true)]
        public string Descriptionk__BackingField {
            get {
                return this.Descriptionk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Descriptionk__BackingFieldField, value) != true)) {
                    this.Descriptionk__BackingFieldField = value;
                    this.RaisePropertyChanged("Descriptionk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MasterEntityCode>k__BackingField", IsRequired=true)]
        public int MasterEntityCodek__BackingField {
            get {
                return this.MasterEntityCodek__BackingFieldField;
            }
            set {
                if ((this.MasterEntityCodek__BackingFieldField.Equals(value) != true)) {
                    this.MasterEntityCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("MasterEntityCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<MasterReferenceID>k__BackingField", IsRequired=true)]
        public long MasterReferenceIDk__BackingField {
            get {
                return this.MasterReferenceIDk__BackingFieldField;
            }
            set {
                if ((this.MasterReferenceIDk__BackingFieldField.Equals(value) != true)) {
                    this.MasterReferenceIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("MasterReferenceIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OriginalEntityCode>k__BackingField", IsRequired=true)]
        public int OriginalEntityCodek__BackingField {
            get {
                return this.OriginalEntityCodek__BackingFieldField;
            }
            set {
                if ((this.OriginalEntityCodek__BackingFieldField.Equals(value) != true)) {
                    this.OriginalEntityCodek__BackingFieldField = value;
                    this.RaisePropertyChanged("OriginalEntityCodek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OriginalReferenceID>k__BackingField", IsRequired=true)]
        public long OriginalReferenceIDk__BackingField {
            get {
                return this.OriginalReferenceIDk__BackingFieldField;
            }
            set {
                if ((this.OriginalReferenceIDk__BackingFieldField.Equals(value) != true)) {
                    this.OriginalReferenceIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("OriginalReferenceIDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ReferenceNumber>k__BackingField", IsRequired=true)]
        public string ReferenceNumberk__BackingField {
            get {
                return this.ReferenceNumberk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberk__BackingFieldField, value) != true)) {
                    this.ReferenceNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("ReferenceNumberk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoucherInfo", Namespace="http://schemas.datacontract.org/2004/07/SystemGroup.Financial.IVoucherManagement." +
        "Common")]
    [System.SerializableAttribute()]
    public partial class VoucherInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DailyNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> MasterEntityRefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.KeyValuePair<string, string>[] ValidationErrorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VoucherDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private VoucherWebService.FinVoucher.AbstractVoucherItemInfo[] VoucherItemInformationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DailyNumber {
            get {
                return this.DailyNumberField;
            }
            set {
                if ((this.DailyNumberField.Equals(value) != true)) {
                    this.DailyNumberField = value;
                    this.RaisePropertyChanged("DailyNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> MasterEntityRef {
            get {
                return this.MasterEntityRefField;
            }
            set {
                if ((this.MasterEntityRefField.Equals(value) != true)) {
                    this.MasterEntityRefField = value;
                    this.RaisePropertyChanged("MasterEntityRef");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Sequence {
            get {
                return this.SequenceField;
            }
            set {
                if ((this.SequenceField.Equals(value) != true)) {
                    this.SequenceField = value;
                    this.RaisePropertyChanged("Sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.KeyValuePair<string, string>[] ValidationErrors {
            get {
                return this.ValidationErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationErrorsField, value) != true)) {
                    this.ValidationErrorsField = value;
                    this.RaisePropertyChanged("ValidationErrors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime VoucherDate {
            get {
                return this.VoucherDateField;
            }
            set {
                if ((this.VoucherDateField.Equals(value) != true)) {
                    this.VoucherDateField = value;
                    this.RaisePropertyChanged("VoucherDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VoucherWebService.FinVoucher.AbstractVoucherItemInfo[] VoucherItemInformation {
            get {
                return this.VoucherItemInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.VoucherItemInformationField, value) != true)) {
                    this.VoucherItemInformationField = value;
                    this.RaisePropertyChanged("VoucherItemInformation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractVoucherItemInfo", Namespace="http://schemas.datacontract.org/2004/07/SystemGroup.Financial.IVoucherManagement." +
        "Common")]
    [System.SerializableAttribute()]
    public partial class AbstractVoucherItemInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RowNumberk__BackingFieldField;
        
        private long VoucherItemIDk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<RowNumber>k__BackingField", IsRequired=true)]
        public int RowNumberk__BackingField {
            get {
                return this.RowNumberk__BackingFieldField;
            }
            set {
                if ((this.RowNumberk__BackingFieldField.Equals(value) != true)) {
                    this.RowNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("RowNumberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<VoucherItemID>k__BackingField", IsRequired=true)]
        public long VoucherItemIDk__BackingField {
            get {
                return this.VoucherItemIDk__BackingFieldField;
            }
            set {
                if ((this.VoucherItemIDk__BackingFieldField.Equals(value) != true)) {
                    this.VoucherItemIDk__BackingFieldField = value;
                    this.RaisePropertyChanged("VoucherItemIDk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FinVoucher.IVoucherService")]
    public interface IVoucherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/RegisterVoucher", ReplyAction="http://tempuri.org/IVoucherService/RegisterVoucherResponse")]
        VoucherWebService.FinVoucher.VoucherInfo RegisterVoucher(VoucherWebService.FinVoucher.VoucherData voucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/RegisterVoucher", ReplyAction="http://tempuri.org/IVoucherService/RegisterVoucherResponse")]
        System.Threading.Tasks.Task<VoucherWebService.FinVoucher.VoucherInfo> RegisterVoucherAsync(VoucherWebService.FinVoucher.VoucherData voucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/ValidateVoucher", ReplyAction="http://tempuri.org/IVoucherService/ValidateVoucherResponse")]
        System.Collections.Generic.KeyValuePair<string, string>[] ValidateVoucher(VoucherWebService.FinVoucher.VoucherData voucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/ValidateVoucher", ReplyAction="http://tempuri.org/IVoucherService/ValidateVoucherResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, string>[]> ValidateVoucherAsync(VoucherWebService.FinVoucher.VoucherData voucher);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/DeleteVoucher", ReplyAction="http://tempuri.org/IVoucherService/DeleteVoucherResponse")]
        void DeleteVoucher(long[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/DeleteVoucher", ReplyAction="http://tempuri.org/IVoucherService/DeleteVoucherResponse")]
        System.Threading.Tasks.Task DeleteVoucherAsync(long[] ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/DeleteVouchersByAuxiliaryNumber", ReplyAction="http://tempuri.org/IVoucherService/DeleteVouchersByAuxiliaryNumberResponse")]
        void DeleteVouchersByAuxiliaryNumber(string auxiliaryNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/DeleteVouchersByAuxiliaryNumber", ReplyAction="http://tempuri.org/IVoucherService/DeleteVouchersByAuxiliaryNumberResponse")]
        System.Threading.Tasks.Task DeleteVouchersByAuxiliaryNumberAsync(string auxiliaryNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/ViewVoucher", ReplyAction="http://tempuri.org/IVoucherService/ViewVoucherResponse")]
        VoucherWebService.FinVoucher.VoucherData ViewVoucher(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/ViewVoucher", ReplyAction="http://tempuri.org/IVoucherService/ViewVoucherResponse")]
        System.Threading.Tasks.Task<VoucherWebService.FinVoucher.VoucherData> ViewVoucherAsync(long id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/ViewVoucherByAuxiliaryNumber", ReplyAction="http://tempuri.org/IVoucherService/ViewVoucherByAuxiliaryNumberResponse")]
        VoucherWebService.FinVoucher.VoucherData[] ViewVoucherByAuxiliaryNumber(string auxiliaryNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVoucherService/ViewVoucherByAuxiliaryNumber", ReplyAction="http://tempuri.org/IVoucherService/ViewVoucherByAuxiliaryNumberResponse")]
        System.Threading.Tasks.Task<VoucherWebService.FinVoucher.VoucherData[]> ViewVoucherByAuxiliaryNumberAsync(string auxiliaryNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVoucherServiceChannel : VoucherWebService.FinVoucher.IVoucherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoucherServiceClient : System.ServiceModel.ClientBase<VoucherWebService.FinVoucher.IVoucherService>, VoucherWebService.FinVoucher.IVoucherService {
        
        public VoucherServiceClient() {
        }
        
        public VoucherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoucherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoucherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoucherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VoucherWebService.FinVoucher.VoucherInfo RegisterVoucher(VoucherWebService.FinVoucher.VoucherData voucher) {
            return base.Channel.RegisterVoucher(voucher);
        }
        
        public System.Threading.Tasks.Task<VoucherWebService.FinVoucher.VoucherInfo> RegisterVoucherAsync(VoucherWebService.FinVoucher.VoucherData voucher) {
            return base.Channel.RegisterVoucherAsync(voucher);
        }
        
        public System.Collections.Generic.KeyValuePair<string, string>[] ValidateVoucher(VoucherWebService.FinVoucher.VoucherData voucher) {
            return base.Channel.ValidateVoucher(voucher);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.KeyValuePair<string, string>[]> ValidateVoucherAsync(VoucherWebService.FinVoucher.VoucherData voucher) {
            return base.Channel.ValidateVoucherAsync(voucher);
        }
        
        public void DeleteVoucher(long[] ids) {
            base.Channel.DeleteVoucher(ids);
        }
        
        public System.Threading.Tasks.Task DeleteVoucherAsync(long[] ids) {
            return base.Channel.DeleteVoucherAsync(ids);
        }
        
        public void DeleteVouchersByAuxiliaryNumber(string auxiliaryNumber) {
            base.Channel.DeleteVouchersByAuxiliaryNumber(auxiliaryNumber);
        }
        
        public System.Threading.Tasks.Task DeleteVouchersByAuxiliaryNumberAsync(string auxiliaryNumber) {
            return base.Channel.DeleteVouchersByAuxiliaryNumberAsync(auxiliaryNumber);
        }
        
        public VoucherWebService.FinVoucher.VoucherData ViewVoucher(long id) {
            return base.Channel.ViewVoucher(id);
        }
        
        public System.Threading.Tasks.Task<VoucherWebService.FinVoucher.VoucherData> ViewVoucherAsync(long id) {
            return base.Channel.ViewVoucherAsync(id);
        }
        
        public VoucherWebService.FinVoucher.VoucherData[] ViewVoucherByAuxiliaryNumber(string auxiliaryNumber) {
            return base.Channel.ViewVoucherByAuxiliaryNumber(auxiliaryNumber);
        }
        
        public System.Threading.Tasks.Task<VoucherWebService.FinVoucher.VoucherData[]> ViewVoucherByAuxiliaryNumberAsync(string auxiliaryNumber) {
            return base.Channel.ViewVoucherByAuxiliaryNumberAsync(auxiliaryNumber);
        }
    }
}
